Events/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('django.contrib.auth.urls')),
    path('users/', include('users.urls')),
    path('', include('tickets.urls')),

]




urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

tickets/urls.py
from django.urls import path
from .views import *

urlpatterns=[
    path('', index, name='index'),

    path('site-admin/', site_admin, name='site_admin'),
    path('search/', searchevents, name='search'),

    path('site-admin/events/<int:id>/delete/', site_admin_ticket_delete, name='site_admin_ticket_delete'),
    path('site-admin/rsvp/<int:id>/delete/', site_admin_rsvp_delete, name='site_admin_rsvp_delete'),


    path('add-category/', home, name='home'),
    path('add-slot/', slot, name='slot'),
    path('add-event/', event, name='event'),
    path('add-ticket/', ticket, name='ticket'),
    path('events/<int:id>/', eventDetail, name='event_details'),
    path('ticket/<int:id>/', ticketDetail, name='ticket_details'),
    path('host/dashboard/', host_dash, name='host_dash'),
    path('host/events/', host_events, name='host_events'),

    path('host/sales/', host_sales, name='host_sales'),


    path('host/events/<int:id>/update/', host_event_edit, name='host_event_edit'),
    path('host/events/<int:id>/delete/', host_event_delete, name='host_event_delete'),
    path('host/ticket/<int:id>/', host_ticket_details, name='host_ticket_details'),
    path('host/ticket/<int:id>/update/', admin_ticket_edit, name='admin_ticket_edit'),
    path('host/ticket/<int:id>/delete/', admin_ticket_delete, name='admin_ticket_delete'),
    path('host/sales/<int:id>/delete/', host_sales_delete, name='host_sales_delete'),

    path('access/token/', getAccessToken, name='get_mpesa_access_token'),
    path('online/lipa/', lipa_na_mpesa_online, name='lipa_na_mpesa'),

        # register, confirmation, validation and callback urls
    path('c2b/register/', register_urls, name="register_mpesa_validation"),
    path('c2b/confirmation/', confirmation, name="confirmation"),
    path('c2b/validation/', validation, name="validation"),
    path('c2b/callback/', call_back, name="call_back"),
]

# register_urls

users/urls.py
from django.urls import path
from .views import *


urlpatterns = [
    path('register/', register, name="register")
]

tickets/models.py
from django.db import models
# from django.contrib.auth.models import User
from phonenumber_field.modelfields import PhoneNumberField
from inclusive_django_range_fields import InclusiveIntegerRangeField
from django.db.models.signals import post_save
from django.dispatch import receiver

from django.contrib.auth import get_user_model

User=get_user_model()

# Create your models here.
class Venue(models.Model):
    name = models.CharField(max_length=300, blank=True, null=True)

    def __str__(self):
        return self.name



class PaymentCategories(models.Model):
    company = models.ForeignKey(User, on_delete=models.CASCADE, blank=True, null=True)
    name = models.CharField(max_length=300, blank=True, null=True)

    def __str__(self):
        return self.name

class Slot(models.Model):
    theatre = models.CharField(max_length=300, blank=True, null=True)
    category = models.ForeignKey(PaymentCategories, on_delete=models.CASCADE, null=True) 
    number_of_seats =  models.PositiveIntegerField()
    from_seat_number = models.PositiveIntegerField(null=True, blank=True)
    to_seat_number = models.PositiveIntegerField(null=True, blank=True)
    company = models.ForeignKey(User, on_delete=models.CASCADE, null=True)


    
    @property
    def seats(self):
        available_seats = [seat for seat in range((self.from_seat_number), (self.to_seat_number +1))]
        return available_seats

    @property
    def numberOfSeats(self):
        # available_seats = [seat for seat in range((self.from_seat_number), (self.to_seat_number +1))]
        return len(self.seats)

    def __str__(self):
        return self.category.name




class Event(models.Model):
    company = models.ForeignKey(User, on_delete=models.CASCADE)
    # owner = models.CharField(max_length=300, blank=True, null=True)
    title = models.CharField(max_length=300, blank=True, null=True)
    description = models.TextField(blank=True, null=True)
    banner = models.FileField(upload_to="events/banners", null=True, blank=True)
    date = models.DateTimeField(null=True, blank=True)
    starting_from = models.TimeField(null=True, blank=True)
    closed = models.BooleanField(default=False)
    available_slots = models.ManyToManyField(Slot, blank=True)

    def __str__(self):
        return self.title

TICKET_CHOICES = (
    ("VVIP", "VVIP"),
    ("VIP", "VIP"),
    ("REGULAR", "REGULAR"),
    ("KIDS", "KIDS"),
    ("ADVANCED", "ADVANCED"),
)
class Ticket(models.Model):
    # ticket_type = models.CharField(max_length = 20,choices = TICKET_CHOICES, default = 'REGULAR')    
    event = models.ForeignKey(Event, on_delete=models.CASCADE)   
    category = models.ForeignKey(PaymentCategories, on_delete=models.CASCADE, null=True) 
    price = models.PositiveIntegerField()


    def __str__(self):
        return f"{self.category.name} going for {self.price}"

class Reservation(models.Model):
    ticket = models.ForeignKey(Ticket, on_delete=models.CASCADE)   
    names = models.CharField(max_length=500, blank=True, null=True)
    email = models.EmailField(max_length=500, blank=True, null=True)
    phone_number = PhoneNumberField()
    row_no = models.CharField(max_length=5, null=True, blank=True) 
    column_no = models.CharField(max_length=5, null=True, blank=True) 

    paid = models.BooleanField(default=False)


    def __str__(self):
        return f"{self.email} reserved {self.ticket.category}"


    
class Eticket(models.Model):
    reservation = models.OneToOneField(Reservation, on_delete=models.CASCADE) 
    seat_no = models.CharField(max_length=20, null=True, blank=True)     
    ticket_class = models.CharField(max_length=20, null=True, blank=True)  

    def __str__(self):
        return f"{self.reservation.names} {self.seat_no} {self.ticket_class}"

# lisst = [1,2,3,4,5]
# for i in range(len(lisst)-1):
#     del lisst[0]

# [2, 3, 4, 5]
# [3, 4, 5]
# [4, 5]
# [5]

@receiver(post_save, sender=Reservation)
def create_eticket(sender, instance, created, **kwargs):
    if created:
        slots = [slot for slot in instance.ticket.event.available_slots.all() if slot.category == instance.ticket.category]
        aseats=[i.seats for i in slots][0]
        seat_no=aseats[0]
        Eticket.objects.create(reservation=instance,ticket_class=str(instance.ticket.category),
        seat_no=seat_no)
        # del aseats[0]

@receiver(post_save, sender=Reservation)
def save_eticket(sender, instance, **kwargs):
    instance.eticket.save()


class BaseModel(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    class Meta:
        abstract = True
# M-pesa Payment models
class MpesaCalls(BaseModel):
    ip_address = models.TextField()
    caller = models.TextField()
    conversation_id = models.TextField()
    content = models.TextField()
    class Meta:
        verbose_name = 'Mpesa Call'
        verbose_name_plural = 'Mpesa Calls'
class MpesaCallBacks(BaseModel):
    ip_address = models.TextField()
    caller = models.TextField()
    conversation_id = models.TextField()
    content = models.TextField()
    class Meta:
        verbose_name = 'Mpesa Call Back'
        verbose_name_plural = 'Mpesa Call Backs'
class MpesaPayment(BaseModel):
    amount = models.DecimalField(max_digits=10, decimal_places=2)
    description = models.TextField()
    type = models.TextField()
    reference = models.TextField()
    first_name = models.CharField(max_length=100)
    middle_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    phone_number = models.TextField()
    organization_balance = models.DecimalField(max_digits=10, decimal_places=2)
    class Meta:
        verbose_name = 'Mpesa Payment'
        verbose_name_plural = 'Mpesa Payments'
    def __str__(self):
        return self.first_name

tickets/forms.py
from django.forms import ModelForm
from .models import *
from django import forms
from datetime import date


class DateInput(forms.DateInput):
    input_type = 'date'

class TimePickerInput(forms.TimeInput):
    input_type = 'time'    

today = date.today()
  

class VenueForm(ModelForm):
    class Meta:
        model = Venue
        fields = "__all__"

class PaymentCategoriesForm(ModelForm):
    class Meta:
        model = PaymentCategories
        fields = ["name"]

class SlotForm(ModelForm):
        # menu = forms.ModelChoiceField(queryset=Menu.objects.filter(id=1))
    # category = forms.ModelChoiceField(queryset=PaymentCategories.objects.none(),)

    class Meta:
        model =  Slot   
        fields = ('theatre','category','number_of_seats','from_seat_number','to_seat_number',)

    # def __init__(self, *args, **kwargs):
    #     request = kwargs.pop('request', None)
    #     super().__init__(*args, **kwargs)
    #     if request:
    #         user = request.user
    #         self.fields['category'].queryset = PaymentCategories.objects.filter(company=user)

        # def __init__(self, user, *args, **kwargs):
        #     super(SlotForm, self).__init__(*args, **kwargs)
        #     self.fields['category'].queryset = PaymentCategories.objects.filter(company=user)

        # def __init__(self, *args, **kwargs):
        #     user = kwargs.pop('user','')
        #     super(SlotForm, self).__init__(*args, **kwargs)
        #     self.fields['category']=forms.ModelChoiceField(queryset=PaymentCategories.objects.filter(company=user))

class EventForm(ModelForm):
    # to include company -User
    # available_slots = forms.ModelMultipleChoiceField(queryset=Slot.objects.none(),)

    class Meta:
        model = Event
        fields = ['title','description','banner','date','starting_from','closed','available_slots']
        widgets = {
            'date': DateInput(attrs={'min': today}),
            'starting_from': TimePickerInput(),
            'description': forms.Textarea(attrs={'cols':4, 'rows':6}),

        } 

        # def __init__(self, user, *args, **kwargs):
        #     super(EventForm, self).__init__(*args, **kwargs)
        #     self.fields['available_slots'].queryset = PaymentCategories.objects.filter(company=user)

class TicketForm(ModelForm):
    # to include Event
    # event = forms.ModelChoiceField(queryset=Event.objects.none(),)
    # category = forms.ModelChoiceField(queryset=PaymentCategories.objects.none(),)


    class Meta:
        model = Ticket
        fields = ['event','category','price']     

                # def __init__(self, user, *args, **kwargs):
        #     super(EventForm, self).__init__(*args, **kwargs)
        #     self.fields['available_slots'].queryset = PaymentCategories.objects.filter(company=user)  

class ReservationForm(ModelForm):
    # to include Ticket
    class Meta:
        model = Reservation
        fields = ['names','email','phone_number','row_no','column_no']

templates/tickets/adminEvents.html
{% extends 'base.html' %}
{% block title %}
Host | Events
{% endblock title %}
   
   
   {% block content %}
    <div class="container mt-2 mb-2">
        <div class="row mt-2 mb-2">
        {% for event in events %}
        <div class="col-md-3 mt-2 mb-2">
                <div class="card shadow-md mt-2 mb-2">
                    <div class="card-body bg-dark">
                        <p class="card-text text-white">{{ event.title }}</p>
                        <p class="card-text text-white">{{ event.description }}</p>
                        <a href="{% url 'host_event_edit' event.id %}" class="text-secondary">Update</a>
                        <a href="{% url 'host_event_delete' event.id %}" class="float-end text-secondary">Delete</a>
                        <div class="mt-2 mb-2">
                        {% for ticket in event.ticket_set.all %}
                        <a href="{% url 'host_ticket_details' ticket.id %}">
                            <span class="badge badge-success">{{ ticket.category }} <strong style="color: brown; font-size: small; font-weight: 800;">ksh: {{ ticket.price }} </strong>
                                {% for slot in ticket.event.available_slots.all %}
                                {% if slot.category == ticket.category %}
                                    {{ slot.numberOfSeats }} seats 
                                {% endif %}
                                {% endfor %}
                                </span>
                                </a>
                                {% endfor %}
                            </div>

                        
                    </div>
                </div>
        </div>
        {% endfor %}
    </div>
    {% if events.has_other_pages %}
    <nav>
      <ul class="pagination justify-content-center">
        {% if events.has_previous %}
          <li class="page-item text-white bg-dark">
            <a class="page-link text-white bg-dark"  href="?page={{ events.previous_page_number }}" aria-label="Previous">
              <span aria-hidden="true">&laquo;</span>
            </a>
          </li>
        {% else %}
          <li class="page-item disabled">
              <span class="page-link" aria-hidden="true">&laquo;</span>
          </li>
        {% endif %}

        {% for p in events.paginator.page_range %}
          {% if events.number == p %}
            <li class="page-item bg-dark"><a class="page-link" style="color: rgb(243, 243, 243);" href="#">{{ p }}</a></li>
          {% else %}
            <li class="page-item bg-dark"><a class="page-link" href="?page={{ p }}">{{ p }}</a></li>
          {% endif %}
        {% endfor %}

        {% if events.has_next %}
          <li class="page-item bg-dark">
            <a class="page-link" href="?page={{ events.next_page_number }}" aria-label="Next">
              <span aria-hidden="true">&raquo;</span>
            </a>
          </li>
        {% else %}
          <li class="page-item disabled bg-dark">
            <span class="page-link" aria-hidden="true">&raquo;</span>
          </li>
        {% endif %}
    </ul>
    </nav>
  {% endif %}
    </div>
    {% endblock content %}

templates/tickets/adminT.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load mathfilters %}
{% block title %}
Host | Tickets
{% endblock title %}
    {% block content %}
    <div class="container mt-2 mb-2">
        <div class="row mt-2 mb-2">
            <div class="col-md-3 mt-2 mb-2"></div>
        <div class="col-md-6 mt-2 mb-2">
                <div class="card shadow-md mt-2 mb-2 bg-dark">
                    <div class="card-body">
                        <h5 class="card-text text-white">{{ ticket.category }} ticket for {{ticket.event}} 
                            going for ksh {{ ticket.price }}</h5>
                        <p class="card-text"> </p>
                        <div class="">
                        {% for rsvp in ticket.reservation_set.all  %}
                        {{rsvp.count}}
                        {% endfor %}
                        {% for slot in ticket.event.available_slots.all %}
                        {% if slot.category == ticket.category %}
                        {% if reservations == slot.numberOfSeats%} 
                        <!-- number_of_slots -->
                    
                        <del>
                        <span class="badge bg-danger" style="font-size: larger; font-weight: 800;">SOLD OUT</span>
                    
                        </del>
                        <p>
                        </p>
                        {% else %}
                        <p class="text-white" >

                        <span class="badge text-danger" style="font-size: medium; font-weight: bold;">{{reservations}}</span>
                        /
                        <span class="badge text-success" style="font-size: medium; font-weight: bold;">{{ slot.numberOfSeats  }}</span>
                        booked</p>
                        <p class="text-white">
                            Sold : Ksh {{reservations|mul:ticket.price }}
                        </p>
                        <p class="text-success">
                            {{slot.numberOfSeats|sub:reservations }}
                            <span class="text-white">available slots</span>

                        </p>


                        {% endif %}
                        {% endif %}
                        {% endfor %}
                    </div>

                        <a class="text-secondary" href="{% url 'admin_ticket_edit' ticket.id %}">Update</a>
                        <a class="text-secondary float-end" href="{% url 'admin_ticket_delete' ticket.id %}">Delete</a>

                    </div>
                </div>

        </div>
        <div class="col-md-3 mt-2 mb-2"></div>

    </div>
    </div>

    {% endblock content %}

templates/tickets/adminTickets.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load mathfilters %}
{% block title %}
Host | Tickets |Details
{% endblock title %}

    {% block content %}

    <div class="container mt-2 mb-2">
        <div class="row mt-2 mb-2">
        <div class="col mt-2 mb-2">
            <div class="col-md-4 mt-4 mb-4 p-3">
                <p class="text-center"></p>
                <form action="" method="post">
                    {% csrf_token %}
                    {{form|crispy}}
                    <button type="submit" class="btn btn-outline-primary btn-lg mt-2"> Save</button>
                </form>

            </div>
        </div>
    </div>
    </div>

    {% endblock content %}

templates/tickets/eventDetails.html
{% extends 'base2.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% load mathfilters %}
{% block title %}
Event | Details
{% endblock title %}
{% block content %}

    <div class="container mt-4 mb-4 align-items-center justify-content-center">
        <div class="row mt-4 mb-4">
            <div class="col-md-4 mt-2 mb-4 p-3">
                <p class="text-center"></p>

            </div>
            <div class="col-md-6 mt-4 mb-4 p-3">
                <p class="text-center"></p>
                {% if event %}
                <div class="card mt-2 mb-2 shadow-lg">
                    <div class="card-body bg-dark text-white">
<!-- available_slots -->
                        <h5 class="card-tittle text-secondary">{{event.title}}</h5>
                        <p class="card-text">{{ event.company.username }} </p>
                        <p class="card-text"> {{ event.description }} </p>
                        <p class="card-text">{{ event.date|date:"Y M d" }} <span class="badge">{{ event.starting_from }}</span></p>
                        
                        <!-- {% for slot in event.available_slots.all %}
                        <span class="badge badge-success">{{ slot.category.name }} {{ slot.number_of_seats }} </span>

                        {% endfor %} -->

                    {% for ticket in tickets %}
                                <a href="{% url 'ticket_details' ticket.id %}" >
                                    
                                    <span class="badge badge-success" id="tick">{{ ticket.category }} <strong style="color: brown; font-size: small; font-weight: 800;">ksh: {{ ticket.price }} </strong>
                                        {% for slot in ticket.event.available_slots.all %}
                                        {% if slot.category == ticket.category %}

                                        <!-- {{ slot.number_of_seats }} seats  -->
                                            {{ slot.numberOfSeats }} seats 

                                        <!-- {{ slot.seats}} -->
                                        {% endif %}
                                        {% endfor %}
                    </span>
                                </a>
                    {% endfor %}
                </div>
            </div>
                {% endif %}
            </div>
            <div class="col-md-4 mt-4 mb-4p-3">
                <p class="text-center"></p>
            </div>

        </div>
    </div>
{% endblock content %}

templates/tickets/events.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load mathfilters %}
{% block title %}
Host | Post
{% endblock title %}

   {% block content %}

    <div class="container mt-4 mb-4 align-items-center justify-content-center">
        <div class="row mt-4 mb-4">
            <div class="col-md-4 mt-4 mb-4 p-3">
                <p class="text-center"></p>


            </div>
            <div class="col-md-4 mt-4 mb-4 p-3">
                <p class="text-center"></p>
                <form action="" method="post" class="text-white">
                    {% csrf_token %}
                    {{form|crispy}}
                    <button type="submit" class="btn btn-outline-secondary text-white btn-lg mt-2">Save</button>
                </form>

            </div>
            <div class="col-md-4 mt-4 mb-4p-3">
                <p class="text-center"></p>

            </div>

        </div>
    </div>

    {% endblock content %}

templates/tickets/hostdash.html
{% extends 'base.html' %}
{% block title %}
Host | Dashboard
{% endblock title %}


    {% block content %}
    <div class="container mt-2 mb-2">
        <div class="row mt-2 mb-2">
        <div class="col-3 mt-2 mb-2">
            <div class="card shadow-md mt-2 mb-2">
                <div class="card-body bg-dark">
                    <h2 class="card-text text-white">EVENTS</h2>
                    <h2 class="card-text text-white">{{events.count}}</h2>
                    <a class="stretched-link text-secondary" href="{% url 'host_events' %}"> View all</a>
                </div>
            </div>       
        </div>

        <div class="col-3 mt-2 mb-2">
                <div class="card shadow-md mt-2 mb-2 bg-dark">
                    <div class="card-body">
                    <h2 class="card-text text-white">SALES</h2>
                        <h2 class="card-text text-white">{{reservations.count}}</h2>
                    <a class="stretched-link text-secondary" href="{% url 'host_sales' %}"> View all</a>

                    </div>
                </div>     
        </div>

    </div>
    </div>


    {% endblock content %}

templates/tickets/hostsales.html
{% extends 'base.html' %}
{% block title %}
Host | Sales
{% endblock title %}
{% block content %}

<div id="addclient" class="container mt-4 mb-4">
    <div class="row mt-4 mb-4">
        <div class="col-md-1"></div>

        <div class=" col-md-10 mt-4 mb-4 shadow-lg">
          <!-- <a href="{% url 'index' %}" class="btn btn-outline-primary btn-md m-2">MPESA</a> -->

            <h6 class="text-uppercase mt-2 mb-2 text-white">All Sales 
            <span class="float-end">

            </span>
        </h6>
        <table class="table align-middle mb-2 bg-white">
            <thead class="bg-light">
              <tr>
                <th>Name</th>
                <th>Email</th>
                <th>Phone</th>
                <th>Event</th>
                <th>Ticket</th>


              </tr>
            </thead>
            {% if reservations  %}
            <tbody>
                
                {% for reservation in reservations %}
              <tr>
                  <td><p class="fw-bold mb-1">{{reservation.names}}</p></td>
                  <td>
                      {{reservation.email}}
                  </td>
                  <td>
                    {{reservation.phone_number}}
                </td>
                <td>
                    {{reservation.ticket.event.title}} 
                </td>
                <td>
                    <span class="badge badge-success">{{reservation.ticket.category}} {{reservation.ticket.price}}</span>
                </td>

                <td>
                </td>
              </tr>
              {% endfor %}

        
            </tbody>
            {% endif %}

          </table>

          <div class="container mt-2 align-items-center justify-content-center">
            <div class="row text-center">


          <nav aria-label="Page navigation example">
              <ul class="pagination ">
                {% if reservations.has_previous %}    
                <li class="page-item">
                  <a href="?page={{ reservations.previous_page_number }}" class="page-link" href="#" aria-label="Previous">
                    <span aria-hidden="true">&laquo;</span>
                  </a>
                </li>
                {% endif %}
                <li class="page-item"><a class="page-link" href="#">
                  page {{ reservations.number }} of {{ reservations.paginator.num_pages }}
                </a></li>
                {% if events.has_next %}
                <li class="page-item">
                  <a href="?page={{ reservations.next_page_number }}" class="page-link" href="#" aria-label="Next">
                    <span aria-hidden="true">&raquo;</span>
                  </a>
                </li>
                {% endif %}
              </ul>
            </nav>
          </div>
        </div>
                        <!-- <p class="card-text">bids</p> -->
                        <!-- {% for itbid in item.bid_set.all %}
                            {{itbid.price}}
                        {%  endfor %} -->



        </div>
        <div class="col-md-1"></div>

    </div>
</div>

{% endblock content %}

templates/tickets/index.html
{% extends 'base2.html' %}
{% block title %}
Home
{% endblock title %}

{% load crispy_forms_tags %}
{% block content %}

    <div class="container mt-4 mb-4 align-items-center justify-content-center">
        <div class="row mt-4 mb-4">
            <div class="col-md-3 mt-4 mb-4 p-3">
                <p class="text-center"></p>
                <a href="{% url 'lipa_na_mpesa' %}" class="btn btn-outline-secondary btn-md text-white">MPESA</a>
                

            </div>
            <div class="col-md-6 mt-4 mb-4 p-3">
                <p class="text-center"></p>
                {% if events %}
                    {% for event in events %}
                    
                        <div class="card mt-2 mb-2 bg-dark shadow-lg" style="border-radius: 0;">
                            <div class="card-body">
                                <h4  class="card-tittle stretched-link text-secondary"> {{ event.title }} </h4>

                                <p class="card-text text-white"> {{ event.company.username }} </p>
                                <p class="card-text text-white text-muted"> {{ event.date }} </p>
                                <a href="{% url 'event_details' event.id %}" class="card-text stretched-link text-white"></a>

                            </div>
                        </div>
                    {% endfor %}
                {% endif %}
            </div>
            <div class="col-md-3 mt-4 mb-4p-3">
                <p class="text-center"></p>
            </div>
            <!-- Card -->

<!-- Card -->

        </div>
        {% if events.has_other_pages %}
        <nav>
          <ul class="pagination justify-content-center">
            {% if events.has_previous %}
              <li class="page-item bg-dark">
                <a class="page-link" href="?page={{ events.previous_page_number }}" aria-label="Previous">
                  <span aria-hidden="true">&laquo;</span>
                </a>
              </li>
            {% else %}
              <li class="page-item disabled bg-dark">
                  <span class="page-link" aria-hidden="true">&laquo;</span>
              </li>
            {% endif %}
    
            {% for p in events.paginator.page_range %}
              {% if events.number == p %}
                <li class="page-item bg-dark"><a class="page-link" style="color: rgb(246, 247, 252);" href="#">{{ p }}</a></li>
              {% else %}
                <li class="page-item bg-dark"><a class="page-link" href="?page={{ p }}">{{ p }}</a></li>
              {% endif %}
            {% endfor %}
    
            {% if events.has_next %}
              <li class="page-item bg-dark">
                <a class="page-link" href="?page={{ events.next_page_number }}" aria-label="Next">
                  <span aria-hidden="true">&raquo;</span>
                </a>
              </li>
            {% else %}
              <li class="page-item disabled bg-dark">
                <span class="page-link" aria-hidden="true">&raquo;</span>
              </li>
            {% endif %}
        </ul>
        </nav>
      {% endif %}
    </div>

{% endblock content %}

templates/tickets/search.html
{% extends 'base2.html' %}
{% block title %}
Search
{% endblock title %}

{% load crispy_forms_tags %}
{% block content %}
<div class="container mt-2 mb-2">
    <div class="row mt-2 mb-2">
{% if results %}
<h4 class="text-center text-white">Results for <b class="text-secondary">{{ request.GET.q }}</b></h4>
<div class="col-md-4"></div>
<div class="col-md-4">


{% for event in results %}

<div class="card mt-2 mb-2 bg-dark shadow-lg" style="border-radius: 0;">
    <div class="card-body">
        <h4  class="card-tittle stretched-link text-secondary"> {{ event.title }} </h4>

        <p class="card-text text-white"> {{ event.company.username }} </p>
        <p class="card-text text-white text-muted"> {{ event.date }} </p>
        <a href="{% url 'event_details' event.id %}" class="card-text stretched-link text-white"></a>

    </div>
</div>

{% endfor %}
</div>
{% else %}
<h4 class="text-center text-white">No search results for this query</h4>


{% endif %}

    </div>
    <div class="col-md-4"></div>
</div>

{% endblock content %}